config/routes.rb
Rails.application.routes.draw do
  get  '/sso/saml' => 'saml#index', as: 'sso_saml'
  post '/sso/saml/acs' => 'saml#acs', as: 'sso_saml_acs'

  resources :experiments

  get '/exp/:id' => 'experiments#serve'

  # Defines the root path route ("/")
  root "experiments#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/experiment.rb
class Experiment < ApplicationRecord
  audited

  belongs_to :created_by_user, class_name: 'User'
  belongs_to :updated_by_user, class_name: 'User'

  validates :title, presence: true
  validates :key, presence: true

  before_validation :generate_key, on: :create

  def to_param
    key
  end

  private

  def generate_key
    self[:key] = SecureRandom.hex(3)
  end
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user

  private

  def authenticate_user
    redirect_to sso_saml_path unless authenticated?
  end

  def authenticated?
    valid_session?
  end

  def valid_session?
    current_user.present?
  end

  def current_user
    if Rails.env.development?
      User.first
    else
      User.find_by(id: session[:current_user_id])
    end
  end
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  skip_before_action :authenticate_user, only: %i[ serve ]
  protect_from_forgery except: :serve

  before_action :set_experiment, only: %i[ show serve edit update destroy ]

  # GET /experiments
  def index
    @experiments = Experiment.all
  end

  # GET /experiments/1
  def show
  end

  def serve
    respond_to do |format|
      format.js {}
      format.css {}
    end
  end

  # GET /experiments/new
  def new
    @experiment = Experiment.new
  end

  # GET /experiments/1/edit
  def edit
  end

  # POST /experiments
  def create
    @experiment = Experiment.new(experiment_params)

    @experiment.created_by_user = User.first
    @experiment.updated_by_user = User.first

    if @experiment.save
      redirect_to @experiment, notice: "Experiment was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /experiments/1
  def update
    @experiment.attributes = experiment_params

    @experiment.updated_by_user = User.first

    if @experiment.save
      redirect_to @experiment, notice: "Experiment was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /experiments/1
  def destroy
    @experiment.destroy
    redirect_to experiments_url, notice: "Experiment was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_experiment
      @experiment = Experiment.find_by!(key: params[:id])
    end

    # Only allow a list of trusted parameters through.
    def experiment_params
      params.require(:experiment).permit(:title, :description, :key, :javascript, :stylesheet, :approved, :created_by_user_id, :updated_by_user_id)
    end
end

app/controllers/saml_controller.rb
require_dependency 'google_saml_configuration'

class SamlController < ApplicationController
  # No authentication necessary here
  skip_before_action :verify_authenticity_token, :authenticate_user

  def index
    request = OneLogin::RubySaml::Authrequest.new
    redirect_to(request.create(saml_settings), allow_other_host: true)
  end

  def acs
    @saml_response = OneLogin::RubySaml::Response.new(params[:SAMLResponse], settings: saml_settings)

    if @saml_response.is_valid?
      user = user_from_response(@saml_response)

      session.merge!(session_details_for_user(user))

      redirect_to root_path
    else
      Rails.logger.warn("[SAML]") { "Invalid Response Errors - #{@saml_response.errors}" }
      render file: "public/401.html", layout: false, status: status
    end
  end

  private

  def saml_settings
    url_base = [request.protocol, request.host_with_port].join
    GoogleSamlConfiguration.new(url_base).settings
  end

  def session_details_for_user(user)
    {
      current_user_id: user.id,
      expires_at: 12.hours.from_now.to_i
    }
  end

  def user_from_response(saml_response)
    User.find_or_create_by(email: saml_response.nameid) do |user|
      given_name = saml_response.attributes['given_name']
      family_name = saml_response.attributes['family_name']

      user.name = [given_name, family_name].join(' ')
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/helpers/saml_helper.rb
module SamlHelper
end

app/views/experiments/_experiment.html.erb
<div id="<%= dom_id experiment %>" class="col-12 col-md-6 col-lg-4">
  <div class="card text-center mb-3">
    <div class="card-body">
      <h5 class="card-title"><%= experiment.title %></h5>
      <small class="text-muted"><%= experiment.created_by_user.name %></small>
      <p><%= experiment.description %></p>

      <div class="mb-3">
        <% if experiment.approved %>
          <span class="badge bg-success py-2"><i class="bi bi-check-circle-fill me-1"></i>Approved</span>
        <% else %>
          <span class="badge bg-secondary py-2"><i class="bi bi-clock-fill me-1"></i>Pending review</span>
        <% end %>
      </div>
      <div class="d-flex align-items-center justify-space-between">
        <div class="input-group me-3">
          <input type="text" class="form-control bg-white" disabled value="<%= experiment.key %>">
          <button class="btn btn-outline-primary" type="button" onclick="javascript: navigator.clipboard.writeText('<%= experiment.key %>')"><i class="bi bi-clipboard"></i></button>
        </div>
        <%= link_to "View experiment", experiment, class: "btn btn-primary flex-fill flex-shrink-0" %>
      </div>
    </div>
  </div>
</div>

app/views/experiments/_form.html.erb
<%= form_with(model: experiment) do |form| %>
  <% if experiment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(experiment.errors.count, "error") %> prohibited this experiment from being saved:</h2>

      <ul>
        <% experiment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-4">
    <label class="form-label"><%= form.label :title %></label>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="mb-4">
    <label class="form-label"><%= form.label :description %></label>
    <%= form.text_area :description, class: 'form-control', rows: 5 %>
  </div>

  <div class="mb-4">
    <label class="form-label"><%= form.label :javascript %></label>
    <code><%= form.text_area :javascript, class: 'form-control', rows: 12 %></code>
  </div>

  <div class="mb-4">
    <label class="form-label"><%= form.label :stylesheet %></label>
    <code><%= form.text_area :stylesheet, class: 'form-control', rows: 12 %></code>
  </div>

  <div class="mb-4">

    <%= form.check_box :approved ,class: 'form-check-input'%>
    <label class="form-check-label"><%= form.label :approved %></label>
  </div>

  <div class="d-flex justify-content-end">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/experiments/edit.html.erb
<div class="py-5 row justify-content-center">
  <div class="col-12 col-md-8">
    <%= render "form", experiment: @experiment %>
  </div>
</div>

app/views/experiments/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="row my-5">
<div class="col-0 col-md-3"></div>
<h1 class="text-md-center col-7 col-md-6">Experiments</h1>
<div class="col-auto col-5 col-md-3 text-end"><%= link_to "New experiment", new_experiment_path, class: "btn btn-primary" %></div>
</div>

<div id="experiments" class="row">
  <% @experiments.each do |experiment| %>
    <%= render experiment %>
  <% end %>
</div>

app/views/experiments/new.html.erb
<h1>New experiment</h1>

<%= render "form", experiment: @experiment %>

<br>

<div>
  <%= link_to "Back to experiments", experiments_path %>
</div>

app/views/experiments/serve.css.erb
<%= raw @experiment.stylesheet %>

app/views/experiments/serve.js.erb
<%= raw @experiment.javascript %>

app/views/experiments/show.css.erb
<%= raw @experiment.stylesheet %>

app/views/experiments/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="row mt-4">
  <div class="col-6">
    <%= link_to experiments_path do %>
      <i class="bi bi-chevron-left me-1"></i>
      <span>Back to experiments</span>
    <% end %>
  </div>
  <div class="col-6 text-end d-flex align-items-center justify-content-end">
    <%= link_to "Edit", edit_experiment_path(@experiment), class: "btn btn-outline-primary me-2" %>
    <%= button_to "Delete", @experiment, method: :delete, class: "btn btn-outline-danger" %>
  </div>
<div>

<div class="text-center mb-4">
  <h1 class="my-3"><%= @experiment.title %></h1>
  <span class="text-muted">Created by: <%= @experiment.created_by_user.name %></span>
  <div class="input-group mx-auto my-3" style="width: 200px">
    <input type="text" class="form-control bg-white" disabled value="<%= @experiment.key %>">
    <button class="btn btn-outline-primary" type="button" onclick="javascript: navigator.clipboard.writeText('<%= @experiment.key %>')"><i class="bi bi-clipboard"></i></button>
  </div>
  <div class="row justify-content-center my-4">
    <div class="col-12 col-md-8 col-lg-6 text-center mb-2">
      <div class="card">
        <div class="card-body">
          <p><%= @experiment.description %></p>
          <div class="mb-3">
            <% if @experiment.approved %>
              <span class="badge bg-success"><i class="bi bi-check-circle-fill me-1"></i>Approved</span>
            <% else %>
              <span class="badge bg-secondary"><i class="bi bi-clock-fill me-1"></i>Pending review</span>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row justify-content-center">
  <div class="col-12 col-md-5 mb-3">
    <strong class="label mb-2 d-block">Javascript:</strong>
    <div class="p-2 border bg-white rounded">
      <code><%= simple_format(@experiment.javascript) %></code>
    </div>
  </div>
  <div class="col-12 col-md-5 mb-3">
    <strong class="label mb-2 d-block">CSS:</strong>
    <div class="p-2 border bg-white rounded">
      <code><%= simple_format(@experiment.stylesheet) %></code>
    </div>
  </div>
  </div>
</div>

app/views/experiments/show.js.erb
<%= raw @experiment.javascript %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Experiments</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="bg-light container-xl">
    <%= yield %>
  </body>
</html>

app/views/saml/acs.html.erb
<h1>Saml#acs</h1>
<p>Find me in app/views/saml/acs.html.erb</p>

app/views/saml/index.html.erb
<h1>Saml#index</h1>
<p>Find me in app/views/saml/index.html.erb</p>